### ISSUE TITLE
time taken to run dromedary training on llama2(7b) llama2(70b)

### ISSUE THREAD

**Issue by ghost** [IBM/Dromedary#12]
Could you please tell me as to how much time would it take to train llama2 on dromedary with A100 gpus(2).

**Comment by Edward-Sun** [comment]
Hi,

For the 70b model, the training on 8 GPUs finishes in one day, so I would assume on 2 GPUs, it finishes in 4 days, if you increase the GRAD_ACCUMULATION hyper-parameter [here](https://github.com/IBM/Dromedary/blob/b6fa1ffbbfb2d5ca0ec4d80fdb470559b79bb38f/training/step3_principle_engraving/scripts/finetune_dromedary2_70b_sft.sh#L18C1-L18C18) from 4 to 16 to main the same global batch size.

For the 7b, it would be much faster, as you can significantly increase the batch size.
