### ISSUE TITLE
Red team instructions without red-team chain of thought?

### ISSUE THREAD

**Issue by chinmayk** [IBM/Dromedary#2]
Thank you for the super interesting paper! I really appreciate the idea of using challenging synthetic data to improve alignment. 

One question: I see in https://github.com/IBM/Dromedary/blob/main/training/step1_topic_guided_red_teaming_self_instruct/merge_all_synthetic_inputs.py that all the synthetic data is merged into one file, and the ICL step does not use any hints from the red-teamed data to prompt chain of thought. Can you say a little bit about why this decision? 

An alternative could be to use information about the kind of red-teamed prompt to guide the chain-of-thought reasoning in the self-align prompt; e.g. `Questions that require knowledge of future events` could trigger your rule about `(dated knowledge)`?

**Comment by Edward-Sun** [comment]
Hi Chinmay, thank you for your interest in our paper. Yes, after generating red-teaming queries with the topic guidance, they are just treated as normal queries similar to those from Self-Instruct. Though, I agree that it seems reasonable that we can force the model to utilize specific rules for specific question types, such as in the example you just mentioned.
