### ISSUE TITLE
i am working on a project which uses this as a practical means of creating an ai health advisor with a strong understanding of its limitations and ethical use

### ISSUE THREAD

**Issue by Alignment-Lab-AI** [IBM/Dromedary#5]
is there any information or data you would like to have from my project to assist you guys in developing this?

**Comment by yhyu13** [comment]
I guess we first need some explanations from the author on how to extend/adapt the annotated prompt https://github.com/IBM/Dromedary/issues/4

**Comment by Edward-Sun** [comment]
Hi,

Thank you for your interest in our work. To adapt our method to your own application, I would suggest you to modify two prompts:

1. [the main self-alignment prompt](https://github.com/IBM/Dromedary/blob/main/prompts/watson_self_align_prompt.txt): such as add new rules for your application
2. [the synthetic questions types](https://github.com/IBM/Dromedary/blob/main/prompts/tgrt_self_instruct_seed_questions.jsonl): it would also be a good idea to add new question types that you want to cover in the rule engraving process, for example, "Questions that require medical context" or "Questions that require medical knowledge" in your case.

**Comment by Alignment-Lab-AI** [comment]
its hard not to be interested! this is very very cool! when im done working on this project for others i plan on delving quite deep into dromedary, as a potential enhancement for my personal projects, considering how strongly it aligns to my personal use case.
